# Generated by Django 3.2 on 2021-04-18 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_auto_20210417_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminregistration',
            old_name='admin',
            new_name='admin_auth',
        ),
        migrations.RenameField(
            model_name='adminregistration',
            old_name='admin_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='adminregistration',
            old_name='admin_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='adminregistration',
            old_name='admin_join',
            new_name='join',
        ),
        migrations.RenameField(
            model_name='adminregistration',
            old_name='admin_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='adminregistration',
            old_name='admin_user_name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='adminregistration',
            name='confrim_password',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminregistration',
            name='password',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
    ]
