# Generated by Django 3.2 on 2021-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_remove_adminregistration_admin_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistration',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
